# card titles

science_fiction_descriptions = {
    "Phase Cloak": "Bends light around an object, making it temporarily invisible.",
    "Mind Drain": "Extracts memories or knowledge directly from a target's mind.",
    "Dilithium Core": "A rare and essential component for powering warp drives in starships.",
    "Bio-Translator": "Implants or devices enabling real-time translation and understanding of alien languages.",
    "Disruptor": "Energy weapon that disrupts molecular bonds, causing disintegration or malfunctions.",
    "Omega Override": "Grants access to restricted or potentially dangerous protocols or systems.",
    "Tricorder Mk. IV": "Advanced multi-function device for scientific analysis, scanning the environment and lifeforms.",
    "Repair Drone": "Autonomous machine using nanobots to repair starship damage.",
    "Time Field": "Creates a localized distortion of time for tactical maneuvers or travel through time.",
    "Meta-Shield": "Advanced energy shield offering superior protection against various attacks.",
    "Cloaking Shard": "Fragment of alien technology providing partial invisibility for starships.",
    "Cold Fusion Reactor": "Clean and efficient energy source achieving nuclear fusion at lower temperatures.",
    "Nanite Disruptor": "Technology specifically designed to disable or destroy harmful nanobots.",
    "Credit Replicator": "Device that can create desired objects from raw materials, often used for commerce.",
    "Gateway Keycard": "Grants access to a network of portals or gateways for faster-than-light travel.",
    "Antimatter Core": "Stores and utilizes antimatter for incredibly powerful energy generation, requiring advanced containment technology.",
    "Precog Implant": "Neural implant enhancing intuition for future events based on probability calculations.",
    "Holodeck Tech": "Creates immersive holographic environments for training, recreation, or deception.",
    "Slipstream Drive": "Enables faster-than-light travel by exploiting a subspace fold, offering efficiency advantages.",
    "Phased Rifle (Overload)": "Fires energy beams with adjustable power, including a risky overload mode for immense firepower.",
    "Universal Translator (Earpiece)": "Discreet earpiece for real-time alien language translation, ideal for covert operations.",
    "Transporter Enhancer": "Expands transporter range and capabilities, allowing safer long-distance travel or breaching barriers.",
    "Tactical Cloaking Field": "Temporary cloaking for battlefield advantages, invisible to sight and basic sensors.",
    "Graviton Beam Emitter": "Fires concentrated graviton beams to crush objects or manipulate gravity for tactical maneuvers.",
    "Modular Combat Armor": "Customizable armor system adapting to different combat scenarios and environments.",
    "Universal Bio-Stimulant": "Rapidly accelerates healing and enhances physical capabilities for a limited time (injection/ingestion).",
    "Portable Holodeck Projector": "Compact device projecting limited holographic environments for training or distraction.",
    "Warp Core Efficiency Module": "Optimizes warp core performance, increasing efficiency and potentially extending starship range.",
    "Advanced Targeting System": "Leads your aim, predicting enemy movement for superior accuracy.",
    "Quantum Teleportation Device": "Beams matter instantly across vast distances, defying limitations of traditional transporters.",
    "Modular Starship Weaponry": "Swappable weapon modules for starships, adapting firepower to diverse threats.",
    "Energy Signature Masker": "Hides a ship's energy signature, deceiving sensors and cloaking your presence.",
    "Personal Translator Implant": "Seamless understanding of alien languages through a discreet brain implant.",
    "Emergency Force Field": "Deploys a temporary energy barrier for personal protection against attacks.",
    "Universal Translator (Eye Implant)": "Real-time language translation through a visual implant, offering a heads-up display for communication.",
    "Advanced Medical Tricorder": "Analyzes injuries, diagnoses illnesses, and offers medical aid with advanced tricorder technology.",
    "Personal Replicator (Rations)": "Creates edible rations on demand, ensuring a steady food supply on the go.",
    "Bio-Weapon Neutralizer": "Disarms and renders biological weapons inert, protecting against harmful pathogens.",
    "Temporal Probe": "Sends data streams through time for reconnaissance or communication with the past/future.",
    "Automated Defense Turret": "Autonomous sentry weapon system, defending locations with programmed protocols.",
}
