events_descriptions = {
  "FTL Travel": "Faster-than-light travel opens the galaxy for exploration.",
  "First Contact": "A signal from deep space hints at alien intelligence.",
  "Hidden Aliens": "A secret society of aliens lives among us.",
  "Underground Refuge": "Ecological crisis forces humanity underground.",
  "AI Awakening": "Machines achieve sentience, blurring the human-tech line.",
  "Alien Invasion": "Hostile extraterrestrials attack Earth.",
  "Psychic Powers": "Humans unlock extraordinary mental abilities.",
  "Cybernetic Integration": "Human bodies merge with advanced technology.",
  "Space Megastructures": "Humans build enormous structures in space.",
  "Time Travel Paradox": "A time travel mission creates a dangerous paradox.",
  "Simulated Reality": "The line between reality and simulation becomes unclear.",
  "Nanomachines Reshape Reality": "Microscopic machines revolutionize every aspect of life.",
  "Uplift of Animal Intelligence": "Animals evolve intelligence, changing the balance of power.",
  "First Hyperintelligent AI": "An AI surpasses human intelligence in all aspects.",
  "Interstellar War": "Humanity faces a war against another spacefaring civilization.",
  "Discovery of Parallel Universes": "Science confirms the existence of alternate realities.",
  "Clone Armies": "Genetically identical soldiers are created for war.",
  "Extinction Event Averted": "Humanity narrowly avoids a global catastrophe.",
  "Post-Apocalyptic Utopia": "After an apocalypse, humanity rebuilds a better society.",
}
