# System names

# system_descriptions = {}

star_system_descriptions = {
    "Planetary Cradle": "A metaphorical term for a star system suspected to harbor numerous planets, potentially including habitable worlds.",
    "Whispering Veil": "A region within a nebula known for its faint, ethereal glow and the presence of a star system shrouded in mystery.",
    "Temporal Anomaly": "A star system exhibiting unusual temporal distortions, attracting the attention of scientists and explorers seeking to understand the phenomenon.",
    "Galactic Gateway": "A hypothetical location within the galaxy believed to be a natural passageway to other regions, a potential stepping stone for interstellar travel.",
    "Binary Haven": "A binary star system known for its stable orbits and favorable conditions, offering a potential safe harbor for exploration or colonization.",
    "Emerald Expanse": "A vast interstellar region shimmering with an emerald hue, likely due to the presence of nebulae or a specific stellar composition.",
    "Sapphire Fields": "A cluster of stars with a distinctive sapphire-like brilliance, potentially a young star-forming region or a collection of hot, massive stars.",
    "Tentacle Rift": "A region warped by a nebula's tendril-like formations, potentially concealing a star system within its depths.",
    "Eternal Dance": "A binary star system locked in a graceful and enduring orbit, creating a mesmerizing celestial spectacle.",
    "Binary Cradle": "A binary star system suspected to be nurturing the formation of planets within its swirling protoplanetary disk.",
    "Tau Gruis": "A Sun-like star system 12.7 light-years away, known for its potential to harbor Earth-like planets and its ongoing exploration efforts.",
    "Pollux System": "A binary star system 33.8 light-years away, consisting of an orange giant (Pollux A) and a fainter white dwarf companion (Pollux B).",
    "Epsilon Indi": "A K-type dwarf star 9.8 light-years distant, known for its stability and potential for hosting rocky planets in its habitable zone.",
    "Deneb System": "A complex star system 1,500 light-years away, containing a bright blue supergiant (Deneb) and several fainter companion stars.",
    "Achernar Star": "The brightest star in the constellation Eridanus, located 144 light-years away, a hot, massive B-type star with a high luminosity.",
    "Fomalhaut System": "A binary star system 25 light-years distant, containing an A-type star (Fomalhaut A) and a fainter M-dwarf companion. Fomalhaut A is known for its vast debris disk, potentially a site of planet formation.",
    "Altair System": "A binary star system 16.8 light-years away, featuring an A-type main sequence star (Altair) and a fainter white dwarf companion. Altair is a hot, rapidly spinning star.",
    "Beta Hydri": "A binary star system 17.6 light-years distant, consisting of a G-type star (Beta Hydri A) and a fainter M-dwarf companion. Beta Hydri A is similar to our Sun in mass and luminosity.",
    "Zeta Doradus": "A triple star system 81 light-years away, containing a binary pair of F-type stars and a more distant K-type companion. The system is known for its beautiful nebulae.",
    "Canopus System": "The brightest star visible from Earth (excluding the Sun), located 319 light-years away. Canopus is a supergiant star over ten times the mass of the Sun.",
    "Vega Frontier": "A metaphorical term for the region surrounding the Vega star system, 25 light-years distant. Vega is a young, bright A-type star, a potential target for future interstellar exploration.",
    "Orion Expanse": "A vast region within the Orion constellation, containing numerous star systems, nebulae, and potential sites for exploration and discovery.",
    "Andromeda Nebula": "The closest large galaxy to our Milky Way, 2.5 million light-years distant, containing billions of stars and a potential target for future interstellar travel.",
    "Beta Centauri": "A triple star system 360 light-years away, containing a binary pair of B-type stars and a more distant K-type star.",
    "Proxima Centauri": "The closest star system to our own at 4.2 light-years, containing a red dwarf star and the potentially habitable exoplanet Proxima b.",
    "Sirius Binary": "The brightest star system in the night sky, located 8.6 light-years away, consisting of a white main sequence star (Sirius A) and a white dwarf companion (Sirius B).",
    "Barnard's Star": "A faint red dwarf star 6 light-years away, known for its high proper motion (movement across the sky) and the search for potential planets.",
    "Wolf 359": "A red dwarf star 7.8 light-years away, notable for a former nearby supernova remnant and its potential for harboring undiscovered planets.",
    "Tau Ceti": "A Sun-like star 11.9 light-years distant, a prime target in the search for exoplanets due to its spectral similarity to our sun and potential for habitable worlds.",
    "Epsilon Eridani": "A K-type star 10.5 light-years away, another prime candidate in the search for exoplanets with a potentially habitable zone and ongoing studies for planetary companions.",
    "Gliese 581": "A red dwarf star 20 light-years away, potentially harboring a rocky super-Earth in its habitable zone.",
    "Luyten's Star": "A faint red dwarf star 12.2 light-years away, known for its very low mass and slow rotation.",
    "TRAPPIST-1": "An ultra-cool dwarf star 39 light-years away, famous for its system of seven Earth-sized planets, several potentially habitable.",
    "Gliese 667C": "A red dwarf star 22 light-years away, with a giant planet discovered in its orbit.",
    "Proxima b": "A rocky exoplanet orbiting Proxima Centauri, the closest star to our solar system, potentially tidally locked.",
    "Gliese 876": "A red dwarf star 15.6 light-years away, with a confirmed four-planet system including a potentially rocky super-Earth.",
    "HD 189733": "An orange dwarf star 63 light-years away, known for its hot Jupiter exoplanet with an atmosphere probed for water vapor.",
    "55 Cancri": "A Sun-like star 40 light-years away, with a confirmed five-planet system including a potentially habitable super-Earth.",
    "Black Hole Heart": "A star system dominated by the presence of a black hole, a region of immense gravity and a potential source of powerful energy.",
    "Silent Watchtower": "A solitary star system on the fringes of explored space, serving as a remote observation post for astronomers and explorers.",
    "Fractured Ring": "A star system with a shattered debris disk, hinting at a violent past collision or the potential formation of planets within the fragments.",
    "Spectral Forge": "A star system known for its intense stellar activity and diverse electromagnetic spectrum, a potential birthplace for new elements or a location for studying stellar evolution.",
    "Echoing Reaches": "A vast and mostly empty region of space, known for its faint echoes of past stellar events or the lingering effects of a powerful supernova.",
    "Quantum Gate": "A hypothetical location theorized to be a point of connection within the quantum realm, potentially allowing for faster-than-light travel or communication.",
    "Binary Dawn": "A binary star system where both stars are reaching the end of their lives, creating a breathtaking spectacle of a double sunrise before their inevitable collapse.",
    "Stardust Cradle": "A nebula known for its swirling clouds of dust and gas, a potential birthplace for new stars and planetary systems.",
    "Vega Frontier": "A metaphorical term for the region surrounding the young, bright Vega star system, 25 light-years distant. A potential hub for future interstellar exploration due to Vega's stability and promise of habitable worlds.",
    "Orion Expanse": "A vast region within the Orion constellation, teeming with nebulae, newborn stars, and established star systems. A popular destination for astronomers and explorers seeking diverse celestial phenomena.",
    "Andromeda Nebula": "The closest large spiral galaxy to our Milky Way, 2.5 million light-years distant. Home to billions of stars and a potential target for future advanced interstellar travel, though the vast distance presents immense challenges.",
    "Crimson Cradle": "A nebula known for its vibrant red hues, likely due to the presence of hydrogen gas and dust. A suspected birthplace for new stars, potentially harboring young stellar systems within its swirling clouds.",
    "Sapphire Veil": "A region within a nebula known for its ethereal glow tinged with a sapphire hue. The presence of a star system shrouded in mystery fuels speculation about its properties and potential discoveries.",
    "Binary Blaze": "A binary star system where both stars are hot and massive, creating a dazzling spectacle of light and energy.  While beautiful, such systems may not be ideal for harboring habitable planets due to intense radiation.",
    "Ghost Nebula": "A faint nebula, its wispy tendrils barely visible.  Despite its elusiveness, astronomers suspect it may harbor a hidden star system or be a remnant of a past stellar event.",
    "Silent Watch": "A solitary star system on the fringes of explored space, far from the bustling core regions. It serves as a remote observation post for astronomers seeking a clear view of the cosmos.",
    "Emerald Reach": "A vast interstellar region shimmering with an emerald hue, likely due to the presence of nebulae or a specific composition of stars within the region.  This area may hold undiscovered star systems waiting to be explored.",
    "Crimson Chasm": "A vast region of space carved by a powerful stellar explosion, leaving behind a breathtaking expanse of dust, gas, and potentially the remnants of a shattered star system.",
    "Twilight Verge": "The outermost fringes of a star system, where the light of the central star weakens and fades into the darkness of interstellar space. This region may harbor icy worlds or unexplored celestial bodies.",
    "Neutron Heart": "A star system dominated by a neutron star, the collapsed core of a massive star.  The immense gravity and potential for powerful energy emissions make this a fascinating, yet potentially hazardous, location for exploration.",
    "Solar Forge": "A star system dominated by a massive, hot star similar to our Sun but in a more active phase of its life cycle. This 'solar forge' is a potential birthplace for heavier elements ejected into space through stellar winds and eruptions.",
    "Crystal Drift": "A vast cloud of dust and ice particles sparkling like celestial diamonds. This 'crystal drift' may be a leftover fragment from a nebula's formation or a potential source of material for future planetary systems.",
    "Whispering Sands": "A vast region of interstellar dust, appearing like a sea of shimmering sand when viewed from afar. This region may hold clues to the formation of stars and planets or harbor undiscovered objects within its swirling clouds.",
    "Quantum Nexus": "A hypothetical location theorized to be a point of convergence within the quantum realm, where the fabric of space-time may be thinner. This 'nexus' could be a key to unlocking faster-than-light travel or advanced communication methods, though its existence remains unproven.",
}
